spring:
    datasource:
        url: jdbc:mysql://81.68.234.49:3306
        username: user
        password: 12345
server:
    port: 8181

mybatis:
#    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations:
        classpath:mybatis/mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



