spring:
    datasource:
        url: jdbc:mysql://localhost:3306/mysql
        username: root
        password: root
server:
    port: 8181

mybatis:
#    config-location: classpath:mybatis/mybatis-config.xml
    mapper-locations:
        classpath:mybatis/mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



